### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by DRT-DISABLED-ACCOUNT** [Cavein254/mobile-first#6]
Hello John, we would like to express our appreciation for the impressive work you have accomplished in your JavaScript code. However, we have noticed that your project is not functioning as expected in Google Chrome and other browsers. To address this issue, we recommend incorporating a CSS reset. This would prevent the default values of the browser from interfering with the styles that you have implemented.

Please find below an example of a CSS reset that you could utilize in your project:

```css
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  list-style: none;
  text-decoration: none;
}
```

By Juan and Juan David 👍
